name: Deploy Frontend to S3

on:
  push:
    branches:
      - develop
      - main

permissions:
  contents: read  # ✅ OIDC 인증 방지

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VITE_MSW_ENABLED: false
      AWS_REGION: us-east-1
      CLOUDFRONT_ID: ${{ github.ref == 'refs/heads/main' && secrets.PROD_CLOUDFRONT_ID || secrets.DEV_CLOUDFRONT_ID }}
      S3_PREFIX: ${{ github.ref == 'refs/heads/main' && 'main' || 'develop' }}
      VITE_API_URL: ${{ github.ref == 'refs/heads/main' && 'https://api.onrank.kr' || 'https://api-dev.onrank.kr' }}
      VITE_FRONTEND_URL: ${{ github.ref == 'refs/heads/main' && 'https://onrank.kr' || 'https://dev.onrank.kr' }}
      VITE_CLOUDFRONT_URL: ${{ github.ref == 'refs/heads/main' && 'https://onrank.kr' || 'https://dev.onrank.kr' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          rm -f package-lock.json
          npm install

      - name: 🔍 Show env vars
        run: |
          echo "⚙️ VITE_API_URL = $VITE_API_URL"
          echo "⚙️ VITE_FRONTEND_URL = $VITE_FRONTEND_URL"
          echo "📦 S3 Prefix = $S3_PREFIX"
          echo "🚀 CloudFront Distribution ID = $CLOUDFRONT_ID"

      - name: ❌ Clean old dist
        run: rm -rf dist

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: true

      - name: 🕵️ Verify current IAM identity
        run: aws sts get-caller-identity

      - name: Verify AWS permissions
        run: |
          aws cloudfront list-distributions --max-items 1
          aws s3 ls s3://${{ secrets.S3_BUCKET }}

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }}/$S3_PREFIX --delete

      - name: ✅ Invalidate CloudFront cache
        run: |
          echo "Creating invalidation for distribution ID: $CLOUDFRONT_ID"
          INVALIDATION_ID=$(aws cloudfront create-invalidation \
            --distribution-id "$CLOUDFRONT_ID" \
            --paths "/*" \
            --query 'Invalidation.Id' \
            --output text)
          echo "Invalidation ID: $INVALIDATION_ID"
          echo "Waiting for invalidation to complete..."
          aws cloudfront wait invalidation-completed \
            --distribution-id "$CLOUDFRONT_ID" \
            --id "$INVALIDATION_ID"
