name: Deploy Frontend to EC2

on:
  push:
    branches: [ main ]  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 배포 디렉토리 생성 (없는 경우)
            mkdir -p /var/www/html/onrank
            
            # 기존 파일 삭제
            rm -rf /var/www/html/onrank/*
            
            # 새 빌드 파일 복사
            scp -r ${{ github.workspace }}/dist/* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/var/www/html/onrank/
            
            # Nginx 설정 (필요한 경우)
            # sudo systemctl restart nginx 